### ISSUE TITLE
Clarification: Arduino Programming Settings

### ISSUE THREAD

**Issue by kerber** [noelportugal/codecard#2]
What Arduino board settings would you recommend for programming the code card? I seem to be having issues with the default for the ESP8266.

Setup: 
1. Followed the [Arduino esp8266 guide](https://github.com/esp8266/Arduino) to setup via board manager.
2. Connect code card to computer. The card is detected as USB-SERIAL CH340.
3. Set the board to 'Generic ESP8266 Module'
4. Load example 'blink' sketch.
5. Upload.

Result:
```
Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "Generic ESP8266 Module, 80 MHz, Flash, ck, 26 MHz, 40MHz, QIO, 512K (no SPIFFS), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Sketch uses 247948 bytes (49%) of program storage space. Maximum is 499696 bytes.
Global variables use 28028 bytes (34%) of dynamic memory, leaving 53892 bytes for local variables. Maximum is 81920 bytes.
warning: espcomm_sync failed
error: espcomm_open failed
error: espcomm_upload_mem failed
error: espcomm_upload_mem failed
```

**Comment by kerber** [comment]
Thanks for the update. I've adjusted to use your settings and I seem to still be having the issue. Is there something I need to do to put the ESP-12F in to flash mode, or is the reset handled by the serial chip?

**Comment by noelportugal** [comment]
Oh yeah... the esp is by default disabled. It only awakens when button A or B are pressed then the first thing that happens on software setting the enable pin to HIGH. Having said that to flash your card you need to hold A or B until it starts uploading (you'll see the dots ......) Also, the board is awake when A and B are pressed together and the "setup" screen with the barcode shows.

**Comment by kerber** [comment]
That did the trick! Thank you!
