### ISSUE TITLE
Can't connect terminal on MacOS

### ISSUE THREAD

**Issue by eldermoraes** [noelportugal/codecard#4]
Hi!

Have just installed the terminal on a MacOS (High Sierra - 10.13.16) and it doesn't recognize the CodeCard. Have also installed the CH340, but no success.

Tried to run:

`ls  /dev/tty.wchusbserialXXX`

But no device where found. Any clue?

Thanks!

**Comment by noelportugal** [comment]
Interesting...Are you connecting straight to a usb-c-to-usb-micro cable or using a hub? Also I found this project that might help https://github.com/adrianmihalko/ch340g-ch34g-ch34x-mac-os-x-driver

**Comment by noelportugal** [comment]
I see. There could be a possibility that the chip is bad :( Have you tried a different cable just for good measure? Sorry for the troubles.

**Comment by eldermoraes** [comment]
Yes, I've tried with 3 different cables in both cards. No lucky!

IMHO it's not a chip problem, because both cards worked well during the event (CodeOne). Maybe some incompatibility with my Macbook? It's a old one (2012)... don't know, maybe some USB issue or something.

Don't be sorry! I'm really enjoying trying to figure it out.

**Comment by eldermoraes** [comment]
Hi,

The problem was really the cable. I was using a charging only one... :-)

Now it's connected. Thanks!
